package com.frenzin.machinemaintain.utills

object Constant {
    const val IS_QR_BOOKED = "IS_QR_BOOKED"
    const val IS_QR_NOT_BOOKED = "IS_QR_NOT_BOOKED"
    const val IS_COME_FORM_DISPATCH = "IS_COME_FORM_DISPATCH"
    const val MACHINE_NAME = "MACHINE_NAME"
    const val MACHINE_SERIAL_NUMBER = "MACHINE_SERIAL_NUMBER"
    const val CUSTOMER_NAME = "CUSTOMER_NAME"
    const val DATE_OF_BOOK = "DATE_OF_BOOK"
    const val MOBILE_NUMBER = "MOBILE_NUMBER"
    const val TAX_INVOICE_NUMBER = "TAX_INVOICE_NUMBER"
    const val LR_NUMBER = "LR_NUMBER"
    const val PI_NUMBER = "PI_NUMBER"
    const val ADDRESS = "ADDRESS"
    const val DIF_NUMBER = "DIF_NUMBER"
    const val TICKET_NUMBER = "TICKET_NUMBER"
    const val INVERT_DATE = "INVERT_DATE"
    const val STATUS = "STATUS"
    const val TICKET_ID = "TICKET_ID"
    const val FOR_RAISE_ACTIVITY = "FOR_RAISE_ACTIVITY"
    const val E_WAY_NUMBER = "E_WAY_NUMBER"
    const val MACHINE_IMAGES = "MACHINE_IMAGES"
    const val CREATED_DATE = "MACHINE_IMAGES"
}